/** Pregnancy danger signs and newborn danger signs. */
import type { HealthProtocol } from "../types";
import { APPROVED_BY, ON_RED_FLAG, option, outcomes, t } from "./shared";

export const pregnancyDangerSigns: HealthProtocol = {
  id: "pregnancy_danger_signs",
  version: "1.0.0",
  title: "Signes de danger pendant la grossesse",
  approvedBy: APPROVED_BY,
  module: "health",
  citations: ["KB-HE-PREG-01", "KB-HE-TRIAGE-01"],
  selfCareContentIds: ["KB-HE-PREG-01"],
  entry: "pregnancy_signs",
  defaultSeverity: 2,
  questions: {
    pregnancy_signs: {
      id: "pregnancy_signs",
      ask: t(
        "Y a-t-il : saignement par le vagin, maux de tête forts avec vue trouble, convulsions, forte douleur du ventre, fièvre, perte des eaux, le bébé ne bouge plus, visage et mains gonflés, difficulté à respirer ?",
        "Ezali na : makila na nzoto ya mwasi, mitu makasi na miso ekomi molili, kobeta nzoto, mpasi makasi ya libumu, fièvre, mai ekiti, mwana azali koningana lisusu te, elongi na maboko efutuki, kopema mpasi ?",
        "Kele na : menga na nitu ya nkento, ntu ya ngolo ti meso me kuma tombe, kunikana, mpasi ya ngolo ya divumu, mwini ya nitu, masa me kulumuka, mwana ke nikana diaka ve, luse ti maboko me vimba, kupema mpasi ?",
        "Kuna: damu ukeni, maumivu makali ya kichwa na kuona giza, degedege, maumivu makali ya tumbo, homa, maji kuvunjika, mtoto hasogei tena, uso na mikono kuvimba, kupumua kwa shida ?",
        "Kudiku: mashi mu tshiseba, dikanda dia mutu dikole ne mêsu mafike, kutshinguluka, dikanda dia difu dikole, luya lua mubidi, mâyi mapueke, muana kena unyunguluka kabidi, mpala ne bianza bivule, kupetesha lupepele bikole ?",
      ),
      type: "multi_yes_no",
      options: [
        option("vaginal_bleeding", t("Saignement par le vagin", "Makila na nzoto ya mwasi", "Menga na nitu ya nkento", "Damu ukeni", "Mashi mu tshiseba")),
        option("headache_vision", t("Maux de tête forts et vue trouble", "Mitu makasi na miso ya molili", "Ntu ya ngolo ti meso ya tombe", "Maumivu makali ya kichwa na kuona giza", "Dikanda dia mutu ne mêsu mafike")),
        option("convulsions", t("Convulsions", "Kobeta nzoto", "Kunikana", "Degedege", "Kutshinguluka")),
        option("severe_abdominal_pain", t("Forte douleur du ventre", "Mpasi makasi ya libumu", "Mpasi ya ngolo ya divumu", "Maumivu makali ya tumbo", "Dikanda dia difu dikole")),
        option("fever", t("Fièvre", "Fièvre", "Mwini ya nitu", "Homa", "Luya lua mubidi")),
        option("water_broke", t("Perte des eaux", "Mai ekiti", "Masa me kulumuka", "Maji kuvunjika", "Mâyi mapueke")),
        option("no_fetal_movement", t("Le bébé ne bouge plus", "Mwana azali koningana te", "Mwana ke nikana ve", "Mtoto hasogei", "Muana kena unyunguluka")),
        option("swelling", t("Visage et mains gonflés", "Elongi na maboko efutuki", "Luse ti maboko me vimba", "Uso na mikono kuvimba", "Mpala ne bianza bivule")),
        option("breathing_difficulty", t("Difficulté à respirer", "Kopema mpasi", "Kupema mpasi", "Kupumua kwa shida", "Kupetesha lupepele bikole")),
        option("none", t("Aucun de ces signes", "Elembo moko te", "Ata kidimbu mosi ve", "Hakuna dalili yoyote", "Katshina tshimanyinu")),
      ],
      redFlags: [
        { id: "RF-PREG-BLEEDING", when: { q: "pregnancy_signs", op: "includes", value: "vaginal_bleeding" }, label: "Saignement vaginal pendant la grossesse" },
        { id: "RF-PREG-PREECLAMPSIA", when: { q: "pregnancy_signs", op: "includes", value: "headache_vision" }, label: "Céphalées et troubles visuels (pré-éclampsie)" },
        { id: "RF-PREG-CONVULSIONS", when: { q: "pregnancy_signs", op: "includes", value: "convulsions" }, label: "Convulsions (éclampsie)" },
        { id: "RF-PREG-ABDOMINAL-PAIN", when: { q: "pregnancy_signs", op: "includes", value: "severe_abdominal_pain" }, label: "Douleur abdominale sévère" },
        { id: "RF-PREG-NO-MOVEMENT", when: { q: "pregnancy_signs", op: "includes", value: "no_fetal_movement" }, label: "Absence de mouvements fœtaux" },
        { id: "RF-PREG-BREATHING", when: { q: "pregnancy_signs", op: "includes", value: "breathing_difficulty" }, label: "Détresse respiratoire chez une femme enceinte" },
      ],
      onRedFlag: ON_RED_FLAG,
      branches: [{ when: { q: "pregnancy_signs", op: "includes", value: "water_broke" }, next: "months_pregnant" }],
      next: "months_pregnant",
    },
    months_pregnant: {
      id: "months_pregnant",
      ask: t(
        "De combien de mois la grossesse est-elle ?",
        "Zemi ezali na sanza boni ?",
        "Divumu kele na bangonda ikwa ?",
        "Mimba ina miezi mingapi ?",
        "Difu didi ne ngondo bungi kayi ?",
      ),
      type: "number",
      redFlags: [
        { id: "RF-PREG-PRETERM-RUPTURE", when: { all: [{ q: "pregnancy_signs", op: "includes", value: "water_broke" }, { q: "months_pregnant", op: "lt", value: 8 }] }, label: "Rupture des membranes avant 8 mois" },
      ],
      onRedFlag: ON_RED_FLAG,
      next: "anc_visits",
    },
    anc_visits: {
      id: "anc_visits",
      ask: t(
        "Combien de consultations prénatales avez-vous déjà faites ?",
        "Osali consultations prénatales (CPN) boni ?",
        "Nge me sala ba CPN ikwa ?",
        "Umefanya kliniki za ujauzito mara ngapi ?",
        "Wakadi wenza ba CPN bungi kayi ?",
      ),
      type: "number",
      optional: true,
      next: "labour_now",
    },
    labour_now: {
      id: "labour_now",
      ask: t(
        "Les contractions ont-elles commencé, régulières et rapprochées ?",
        "Mpasi ya kobota ebandi, mbala na mbala mpe pene-pene ?",
        "Mpasi ya kubuta me yantika, mbala na mbala mpi pene-pene ?",
        "Uchungu wa kuzaa umeanza, wa mfululizo na wa karibu ?",
        "Makenga a kulela makadi mabanga, misangu ne misangu ne pabuipi ?",
      ),
      type: "yes_no",
      optional: true,
      next: null,
    },
  },
  rules: [
    { id: "R-PREG-FEVER", when: { q: "pregnancy_signs", op: "includes", value: "fever" }, severity: 3 },
    { id: "R-PREG-SWELLING", when: { q: "pregnancy_signs", op: "includes", value: "swelling" }, severity: 3 },
    { id: "R-PREG-TERM-RUPTURE", when: { all: [{ q: "pregnancy_signs", op: "includes", value: "water_broke" }, { q: "months_pregnant", op: "gte", value: 8 }] }, severity: 3 },
    { id: "R-PREG-LABOUR", when: { q: "labour_now", op: "eq", value: true }, severity: 3 },
    { id: "R-PREG-NO-ANC", when: { q: "anc_visits", op: "lt", value: 1 }, severity: 2 },
    { id: "R-PREG-THIRD-TRIMESTER", when: { q: "months_pregnant", op: "gte", value: 8 }, severity: 2 },
  ],
  outcomes: outcomes({
    severity_2: {
      action: "GO_ANC_24H",
      text: t(
        "Allez à la consultation prénatale du centre de santé dans les 24 heures. Emportez le carnet de grossesse, dormez sous une moustiquaire et buvez de l'eau propre. Partez immédiatement en cas de saignement, de convulsions ou de forte douleur.",
        "Kende na CPN ya centre de santé na kati ya ngonga 24. Kamata carnet ya zemi, lala na moustiquaire mpe mela mai ya peto. Kende mbala moko soki makila ebimi, kobeta nzoto to mpasi makasi.",
        "Kwenda na CPN ya centre de santé na kati ya bangunga 24. Baka mukanda ya divumu, lala na muskitiere mpi nwa masa ya bunkete. Kwenda ntangu yayi kana menga me basika, kunikana to mpasi ya ngolo.",
        "Nenda kliniki ya ujauzito ndani ya saa 24. Chukua kadi ya ujauzito, lala ndani ya chandarua na kunywa maji safi. Nenda mara moja ukiona damu, degedege au maumivu makali.",
        "Ndaku ku CPN ku tshibambalu tshia bukolame munda mua midi 24. Angata mukanda wa difu, lala mu tshilamba tshia mikupa ne nua mâyi mimpe. Ndaku mpindieu bikala mashi apatuke, kutshinguluka anyi makenga makole.",
      ),
    },
  }),
};

export const newbornDangerSigns: HealthProtocol = {
  id: "newborn_danger_signs",
  version: "1.0.0",
  title: "Signes de danger du nouveau-né (0 à 28 jours)",
  approvedBy: APPROVED_BY,
  module: "health",
  citations: ["KB-HE-NEWB-01", "KB-HE-TRIAGE-01"],
  selfCareContentIds: ["KB-HE-NEWB-01"],
  entry: "newborn_signs",
  defaultSeverity: 2,
  questions: {
    newborn_signs: {
      id: "newborn_signs",
      ask: t(
        "Le bébé présente-t-il : refus de téter, convulsions, respiration rapide ou difficile, corps froid ou brûlant, absence de mouvement, nombril rouge avec du pus, paumes et plantes jaunes, fontanelle bombée ?",
        "Bébé azali na : koboya komela mabele, kobeta nzoto, kopema mbangu to mpasi, nzoto ya malili to ya moto makasi, koningana te, motolu ya motane na pus, maboko na makolo ya mbuma, mbunzu etomboki ?",
        "Mwana ke na : kubuya kunwa mabele, kunikana, kupema nswalu to mpasi, nitu ya madidi to ya mwini mingi, kunikana ve, ntulu ya mbwaki ti pus, maboko ti makulu ya bunzenza, mbunzu me tomboka ?",
        "Mtoto ana: kukataa kunyonya, degedege, kupumua haraka au kwa shida, mwili baridi au moto sana, kutosogea, kitovu chekundu chenye usaha, viganja na nyayo za njano, utosi kuvimba ?",
        "Muana udi ne: kubenga kuamua, kutshinguluka, kupetesha lupepele lubilu anyi bikole, mubidi wa mashika anyi wa luya bikole, kubenga kunyunguluka, mukaba mukunze ne mafi, bianza ne makasa bia nzenza, tshianza tshia mutu tshivule ?",
      ),
      type: "multi_yes_no",
      options: [
        option("not_feeding", t("Refuse de téter", "Aboyi komela mabele", "Ke buya kunwa mabele", "Anakataa kunyonya", "Udi ubenga kuamua")),
        option("convulsions", t("Convulsions", "Kobeta nzoto", "Kunikana", "Degedege", "Kutshinguluka")),
        option("breathing", t("Respiration rapide ou difficile", "Kopema mbangu to mpasi", "Kupema nswalu to mpasi", "Kupumua haraka au kwa shida", "Kupetesha lupepele lubilu anyi bikole")),
        option("temperature", t("Corps froid ou brûlant", "Nzoto ya malili to ya moto makasi", "Nitu ya madidi to ya mwini mingi", "Mwili baridi au moto sana", "Mubidi wa mashika anyi wa luya")),
        option("no_movement", t("Ne bouge presque plus", "Azali koningana lisusu te", "Ke nikana diaka ve", "Hasogei tena", "Kena unyunguluka kabidi")),
        option("umbilical_pus", t("Nombril rouge avec du pus", "Motolu ya motane na pus", "Ntulu ya mbwaki ti pus", "Kitovu chekundu chenye usaha", "Mukaba mukunze ne mafi")),
        option("jaundice_palms", t("Paumes et plantes jaunes", "Maboko na makolo ya mbuma", "Maboko ti makulu ya bunzenza", "Viganja na nyayo za njano", "Bianza ne makasa bia nzenza")),
        option("bulging_fontanelle", t("Fontanelle bombée", "Mbunzu etomboki", "Mbunzu me tomboka", "Utosi kuvimba", "Tshianza tshia mutu tshivule")),
        option("none", t("Aucun de ces signes", "Elembo moko te", "Ata kidimbu mosi ve", "Hakuna dalili yoyote", "Katshina tshimanyinu")),
      ],
      redFlags: [
        { id: "RF-NEWB-NOT-FEEDING", when: { q: "newborn_signs", op: "includes", value: "not_feeding" }, label: "Refus de téter chez le nouveau-né" },
        { id: "RF-NEWB-CONVULSIONS", when: { q: "newborn_signs", op: "includes", value: "convulsions" }, label: "Convulsions néonatales" },
        { id: "RF-NEWB-BREATHING", when: { q: "newborn_signs", op: "includes", value: "breathing" }, label: "Détresse respiratoire néonatale" },
        { id: "RF-NEWB-TEMPERATURE", when: { q: "newborn_signs", op: "includes", value: "temperature" }, label: "Hypothermie ou fièvre néonatale" },
        { id: "RF-NEWB-NO-MOVEMENT", when: { q: "newborn_signs", op: "includes", value: "no_movement" }, label: "Absence de mouvement" },
        { id: "RF-NEWB-JAUNDICE", when: { q: "newborn_signs", op: "includes", value: "jaundice_palms" }, label: "Ictère des paumes et des plantes" },
        { id: "RF-NEWB-FONTANELLE", when: { q: "newborn_signs", op: "includes", value: "bulging_fontanelle" }, label: "Fontanelle bombée" },
      ],
      onRedFlag: ON_RED_FLAG,
      next: "age_days",
    },
    age_days: {
      id: "age_days",
      ask: t(
        "Quel âge a le bébé, en jours ?",
        "Bébé azali na mikolo boni ?",
        "Mwana kele na bilumbu ikwa ?",
        "Mtoto ana siku ngapi ?",
        "Muana udi ne matuku bungi kayi ?",
      ),
      type: "days",
      next: "low_birth_weight",
    },
    low_birth_weight: {
      id: "low_birth_weight",
      ask: t(
        "Le bébé est-il né très petit, ou avant terme ?",
        "Bébé abotamaki moke mingi, to liboso ya ngonga ?",
        "Mwana butukaka fioti mingi, to na ntwala ya ntangu ?",
        "Mtoto alizaliwa mdogo sana, au kabla ya wakati ?",
        "Muana wakaledibua mukese bikole, anyi kumpala kua tshikondo ?",
      ),
      type: "yes_no",
      optional: true,
      next: "birth_place",
    },
    birth_place: {
      id: "birth_place",
      ask: t(
        "Où l'accouchement a-t-il eu lieu : centre de santé, maison, ou autre ?",
        "Kobota esalemaki wapi : centre de santé, ndako, to esika mosusu ?",
        "Kubuta salamaka wapi : centre de santé, nzo, to kisika ya nkaka ?",
        "Kujifungua kulifanyika wapi: kituo cha afya, nyumbani, au mahali pengine ?",
        "Kulela kuvua kuenzeka penyi: ku tshibambalu tshia bukolame, ku nzubu, anyi muaba mukuabu ?",
      ),
      type: "choice",
      options: [
        option("facility", t("Centre de santé", "Centre de santé", "Centre de santé", "Kituo cha afya", "Tshibambalu tshia bukolame")),
        option("home", t("À la maison", "Na ndako", "Na nzo", "Nyumbani", "Ku nzubu")),
        option("other", t("Ailleurs", "Esika mosusu", "Kisika ya nkaka", "Mahali pengine", "Muaba mukuabu")),
      ],
      next: "exclusive_breastfeeding",
    },
    exclusive_breastfeeding: {
      id: "exclusive_breastfeeding",
      ask: t(
        "Le bébé reçoit-il uniquement le lait maternel, sans eau ni autre aliment ?",
        "Bébé azali komela kaka mabele ya mama, mai to bilei mosusu te ?",
        "Mwana ke nwa kaka mabele ya mama, masa to madia ya nkaka ve ?",
        "Mtoto ananyonya maziwa ya mama pekee, bila maji au chakula kingine ?",
        "Muana udi uamua anu mabele a mamu, kabiyi mâyi anyi biakudia bikuabu ?",
      ),
      type: "yes_no",
      optional: true,
      next: null,
    },
  },
  rules: [
    { id: "R-NEWB-UMBILICAL-INFECTION", when: { q: "newborn_signs", op: "includes", value: "umbilical_pus" }, severity: 3 },
    { id: "R-NEWB-FIRST-WEEK", when: { q: "age_days", op: "lt", value: 7 }, severity: 3 },
    { id: "R-NEWB-LOW-BIRTH-WEIGHT", when: { q: "low_birth_weight", op: "eq", value: true }, severity: 3 },
    { id: "R-NEWB-HOME-BIRTH", when: { q: "birth_place", op: "eq", value: "home" }, severity: 2 },
    { id: "R-NEWB-BIRTH-ELSEWHERE", when: { q: "birth_place", op: "eq", value: "other" }, severity: 2 },
    { id: "R-NEWB-NOT-EXCLUSIVE", when: { q: "exclusive_breastfeeding", op: "eq", value: false }, severity: 2 },
  ],
  outcomes: outcomes({
    severity_2: {
      action: "NEWBORN_CHECK_24H",
      text: t(
        "Faites voir le bébé au centre de santé dans les 24 heures pour la visite du nouveau-né et les vaccins. Gardez-le au chaud contre la peau de sa mère, allaitez souvent, ne mettez rien sur le nombril.",
        "Mema bébé na centre de santé na kati ya ngonga 24 mpo na visite ya nouveau-né mpe bavaccins. Batela ye moto na loposo ya mama, melisa mbala mingi, tia eloko te na motolu.",
        "Nata mwana na centre de santé na kati ya bangunga 24 sambu na visite ya mwana ya mpa ti bavaksa. Bumba yandi mwini na nkanda ya mama, nwisa mbala mingi, tula kima ve na ntulu.",
        "Mpeleke mtoto kituo cha afya ndani ya saa 24 kwa uchunguzi wa mtoto mchanga na chanjo. Mwekeni joto kifuani mwa mama, mnyonyeshe mara kwa mara, usiweke kitu chochote kwenye kitovu.",
        "Tuala muana ku tshibambalu tshia bukolame munda mua midi 24 bua ditangila dia muana mupiamupia ne mavaksa. Mumulame ne luya ku tshiseba tshia mamu, mumuamuishe misangu ya bungi, kutedi tshintu ku mukaba.",
      ),
    },
  }),
};
