/** Fever protocols — child under five (PCIME communautaire) and adult. */
import type { HealthProtocol } from "../types";
import {
  APPROVED_BY,
  ASK_AGE_MONTHS,
  ASK_FEVER_DAYS,
  ASK_MALARIA_TEST,
  DANGER_ASK,
  DANGER_OPTIONS,
  MALARIA_TEST_OPTIONS,
  ON_RED_FLAG,
  dangerRedFlags,
  option,
  outcomes,
  t,
} from "./shared";

export const childFeverU5: HealthProtocol = {
  id: "child_fever_u5",
  version: "1.0.0",
  title: "Fièvre chez l'enfant de moins de 5 ans",
  approvedBy: APPROVED_BY,
  module: "health",
  citations: ["KB-HE-FEVER-01", "KB-HE-PREV-01", "KB-HE-TRIAGE-01"],
  selfCareContentIds: ["KB-HE-FEVER-01", "KB-HE-PREV-01"],
  entry: "danger_signs",
  defaultSeverity: 2,
  questions: {
    danger_signs: {
      id: "danger_signs",
      ask: DANGER_ASK,
      type: "multi_yes_no",
      options: DANGER_OPTIONS,
      redFlags: dangerRedFlags("FEVU5"),
      onRedFlag: ON_RED_FLAG,
      next: "age_months",
    },
    age_months: {
      id: "age_months",
      ask: ASK_AGE_MONTHS,
      type: "age_months",
      redFlags: [
        { id: "RF-FEVU5-NEONATE-FEVER", when: { q: "age_months", op: "lt", value: 2 }, label: "Fièvre chez un nourrisson de moins de 2 mois" },
      ],
      onRedFlag: ON_RED_FLAG,
      next: "fever_days",
    },
    fever_days: {
      id: "fever_days",
      ask: ASK_FEVER_DAYS,
      type: "days",
      next: "malaria_test",
    },
    malaria_test: {
      id: "malaria_test",
      ask: ASK_MALARIA_TEST,
      type: "choice",
      options: MALARIA_TEST_OPTIONS,
      branches: [{ when: { q: "malaria_test", op: "eq", value: "positive" }, next: "rash" }],
      next: "rash",
    },
    rash: {
      id: "rash",
      ask: t(
        "L'enfant a-t-il une éruption sur la peau avec les yeux rouges ou la bouche abîmée ?",
        "Mwana azali na matono na loposo elongo na miso ya motane to monoko ebeba ?",
        "Mwana kele na bitono na nkanda ti meso ya mbwaki to munoko me beba ?",
        "Mtoto ana upele ngozini pamoja na macho mekundu au mdomo uliochubuka ?",
        "Muana udi ne bipupu ku tshiseba ne mêsu makunze anyi mukana mununyanguke ?",
      ),
      type: "yes_no",
      next: "drinking",
    },
    drinking: {
      id: "drinking",
      ask: t(
        "L'enfant boit-il normalement, moins que d'habitude, ou refuse-t-il ?",
        "Mwana azali komela malamu, moke koleka momesano, to aboyi ?",
        "Mwana ke nwa mbote, fioti kuluta mpila ya mbote, to ke buya ?",
        "Mtoto ananywa kama kawaida, kidogo kuliko kawaida, au anakataa ?",
        "Muana udi unua bimpe, bitupa bikese kupita bu kashidi, anyi udi ubenga ?",
      ),
      type: "choice",
      options: [
        option("normal", t("Normalement", "Malamu", "Mbote", "Kama kawaida", "Bimpe")),
        option("less", t("Moins que d'habitude", "Moke koleka momesano", "Fioti kuluta", "Kidogo kuliko kawaida", "Bitupa bikese")),
        option("refuses", t("Refuse de boire", "Aboyi komela", "Ke buya kunwa", "Anakataa kunywa", "Udi ubenga kunua")),
      ],
      redFlags: [
        { id: "RF-FEVU5-REFUSES-DRINK", when: { q: "drinking", op: "eq", value: "refuses" }, label: "Refus total de boire" },
      ],
      onRedFlag: ON_RED_FLAG,
      next: null,
    },
  },
  rules: [
    { id: "R-FEVU5-FEVER-7D", when: { q: "fever_days", op: "gte", value: 7 }, severity: 3 },
    { id: "R-FEVU5-FEVER-3D", when: { q: "fever_days", op: "gte", value: 3 }, severity: 3 },
    { id: "R-FEVU5-INFANT-U12M", when: { all: [{ q: "age_months", op: "gte", value: 2 }, { q: "age_months", op: "lt", value: 12 }] }, severity: 3 },
    { id: "R-FEVU5-MALARIA-POSITIVE", when: { q: "malaria_test", op: "eq", value: "positive" }, severity: 3 },
    { id: "R-FEVU5-MALARIA-UNTESTED", when: { q: "malaria_test", op: "eq", value: "not_done" }, severity: 2 },
    { id: "R-FEVU5-MEASLES-SUSPECT", when: { q: "rash", op: "eq", value: true }, severity: 3 },
    { id: "R-FEVU5-DRINKING-LESS", when: { q: "drinking", op: "eq", value: "less" }, severity: 2 },
  ],
  outcomes: outcomes({
    severity_2: {
      action: "GO_CLINIC_24H_MALARIA_TEST",
      text: t(
        "Faites tester l'enfant pour le paludisme au centre de santé dans les 24 heures. En attendant : faites boire souvent de l'eau propre, découvrez-le, continuez l'allaitement ou les repas.",
        "Kende kotesta mwana palu na centre de santé na kati ya ngonga 24. Na ntango wana : pesa mai ya peto mbala mingi, longola bilamba ya mingi, kokoba komelisa to kolia.",
        "Kwenda kuteste mwana palu na centre de santé na kati ya bangunga 24. Na ntangu yina : pesa masa ya bunkete mbala mingi, katula bilele ya mingi, landa kunwisa mabele to kudia.",
        "Mpeleke mtoto apimwe malaria kituoni ndani ya saa 24. Wakati huo: mnywesheni maji safi mara kwa mara, mvueni nguo nzito, endelea kunyonyesha au kula.",
        "Ndaku ne muana bua kumupima malaria ku tshibambalu munda mua midi 24. Mu tshikondo etshi: mumunuishe mâyi mimpe misangu ya bungi, mumuumbule bilamba bia bungi, tungunuka kumuamuisha anyi kumudisha.",
      ),
    },
  }),
};

export const adultFever: HealthProtocol = {
  id: "adult_fever",
  version: "1.0.0",
  title: "Fièvre chez l'adolescent et l'adulte",
  approvedBy: APPROVED_BY,
  module: "health",
  citations: ["KB-HE-FEVER-01", "KB-HE-EPID-01", "KB-HE-TRIAGE-01"],
  selfCareContentIds: ["KB-HE-FEVER-01", "KB-HE-PREV-01"],
  entry: "danger_signs",
  defaultSeverity: 1,
  questions: {
    danger_signs: {
      id: "danger_signs",
      ask: DANGER_ASK,
      type: "multi_yes_no",
      options: DANGER_OPTIONS,
      redFlags: dangerRedFlags("FEVAD"),
      onRedFlag: ON_RED_FLAG,
      next: "pregnant",
    },
    pregnant: {
      id: "pregnant",
      ask: t(
        "La personne est-elle enceinte ?",
        "Moto yango azali na zemi ?",
        "Muntu yina kele na divumu ?",
        "Je mtu huyu ni mjamzito ?",
        "Muntu eu udi ne difu ?",
      ),
      type: "yes_no",
      optional: true,
      branches: [{ when: { q: "pregnant", op: "eq", value: true }, next: "fever_days" }],
      next: "fever_days",
    },
    fever_days: {
      id: "fever_days",
      ask: ASK_FEVER_DAYS,
      type: "days",
      next: "malaria_test",
    },
    malaria_test: {
      id: "malaria_test",
      ask: ASK_MALARIA_TEST,
      type: "choice",
      options: MALARIA_TEST_OPTIONS,
      next: "other_symptoms",
    },
    other_symptoms: {
      id: "other_symptoms",
      ask: t(
        "Y a-t-il aussi : yeux ou urines jaunes, sang dans les urines, maux de tête très forts, toux depuis plus de deux semaines, éruption sur la peau ?",
        "Ezali lisusu na : miso to masuba ya mbuma, makila na masuba, mitu makasi, kosukola koleka poso mibale, matono na loposo ?",
        "Kele mpi na : meso to masuba ya bunzenza, menga na masuba, ntu ya ngolo, kosukumuna kuluta mposo zole, bitono na nkanda ?",
        "Kuna pia: macho au mkojo wa njano, damu kwenye mkojo, maumivu makali ya kichwa, kikohozi zaidi ya wiki mbili, upele ngozini ?",
        "Kudiku kabidi: mêsu anyi tulua tua nzenza, mashi mu tulua, dikanda dia mutu dia bukole, tshikosolo tshia kupita mbingu ibidi, bipupu ku tshiseba ?",
      ),
      type: "multi_yes_no",
      options: [
        option("yellow_eyes", t("Yeux ou urines jaunes", "Miso to masuba ya mbuma", "Meso to masuba ya bunzenza", "Macho au mkojo wa njano", "Mêsu anyi tulua tua nzenza")),
        option("blood_in_urine", t("Sang dans les urines", "Makila na masuba", "Menga na masuba", "Damu kwenye mkojo", "Mashi mu tulua")),
        option("severe_headache", t("Maux de tête très forts", "Mitu makasi mingi", "Ntu ya ngolo mingi", "Maumivu makali ya kichwa", "Dikanda dia mutu dia bukole")),
        option("cough_2weeks", t("Toux depuis plus de deux semaines", "Kosukola koleka poso mibale", "Kosukumuna kuluta mposo zole", "Kikohozi zaidi ya wiki mbili", "Tshikosolo tshia kupita mbingu ibidi")),
        option("rash", t("Éruption sur la peau", "Matono na loposo", "Bitono na nkanda", "Upele ngozini", "Bipupu ku tshiseba")),
        option("none", t("Aucun", "Moko te", "Ata mosi ve", "Hakuna", "Katshina")),
      ],
      next: null,
    },
  },
  rules: [
    { id: "R-FEVAD-PREGNANT", when: { q: "pregnant", op: "eq", value: true }, severity: 3 },
    { id: "R-FEVAD-FEVER-7D", when: { q: "fever_days", op: "gte", value: 7 }, severity: 3 },
    { id: "R-FEVAD-FEVER-3D", when: { q: "fever_days", op: "gte", value: 3 }, severity: 2 },
    { id: "R-FEVAD-MALARIA-POSITIVE", when: { q: "malaria_test", op: "eq", value: "positive" }, severity: 3 },
    { id: "R-FEVAD-MALARIA-UNTESTED", when: { q: "malaria_test", op: "eq", value: "not_done" }, severity: 2 },
    { id: "R-FEVAD-JAUNDICE", when: { q: "other_symptoms", op: "includes", value: "yellow_eyes" }, severity: 3 },
    { id: "R-FEVAD-HAEMATURIA", when: { q: "other_symptoms", op: "includes", value: "blood_in_urine" }, severity: 3 },
    { id: "R-FEVAD-SEVERE-HEADACHE", when: { q: "other_symptoms", op: "includes", value: "severe_headache" }, severity: 3 },
    { id: "R-FEVAD-TB-SUSPECT", when: { q: "other_symptoms", op: "includes", value: "cough_2weeks" }, severity: 2 },
    { id: "R-FEVAD-RASH", when: { q: "other_symptoms", op: "includes", value: "rash" }, severity: 2 },
  ],
  outcomes: outcomes(),
};
