/** Injuries: wounds, bleeding, burns, head injury, snake and animal bites. */
import type { HealthProtocol } from "../types";
import { APPROVED_BY, ON_RED_FLAG, option, outcomes, t } from "./shared";

export const injuryBleeding: HealthProtocol = {
  id: "injury_bleeding",
  version: "1.0.0",
  title: "Blessures, saignements, brûlures et morsures",
  approvedBy: APPROVED_BY,
  module: "health",
  citations: ["KB-HE-INJ-01", "KB-HE-TRIAGE-01"],
  selfCareContentIds: ["KB-HE-INJ-01"],
  entry: "conscious",
  defaultSeverity: 1,
  questions: {
    conscious: {
      id: "conscious",
      ask: t(
        "La personne est-elle consciente et répond-elle quand on lui parle ?",
        "Moto azali na mayele mpe azali koyanola tango bazali koloba na ye ?",
        "Muntu kele na mayele mpi ke vutula ntangu bo ke tuba ti yandi ?",
        "Je mtu ana fahamu na anajibu anapoongeshwa ?",
        "Muntu udi ne meji ne udi wandamuna padi bamuakula nende ?",
      ),
      type: "yes_no",
      redFlags: [{ id: "RF-INJ-UNCONSCIOUS", when: { q: "conscious", op: "eq", value: false }, label: "Victime inconsciente" }],
      onRedFlag: ON_RED_FLAG,
      next: "bleeding_controlled",
    },
    bleeding_controlled: {
      id: "bleeding_controlled",
      ask: t(
        "Le saignement s'arrête-t-il quand on appuie fort avec un linge propre pendant dix minutes ?",
        "Makila ezali kotelema soki ofini makasi na elamba ya peto miniti zomi ?",
        "Menga ke telama kana nge ke fina ngolo ti dilele ya bunkete miniti kumi ?",
        "Damu inasimama ukibonyeza kwa nguvu na kitambaa safi kwa dakika kumi ?",
        "Mashi adi aimana bikala ukuata ne tshilamba tshimpe ne bukole minite dikumi ?",
      ),
      type: "yes_no",
      redFlags: [{ id: "RF-INJ-UNCONTROLLED-BLEEDING", when: { q: "bleeding_controlled", op: "eq", value: false }, label: "Hémorragie non contrôlée" }],
      onRedFlag: ON_RED_FLAG,
      next: "injury_type",
    },
    injury_type: {
      id: "injury_type",
      ask: t(
        "De quel type de blessure s'agit-il : plaie ou coupure, brûlure, chute ou fracture, morsure de serpent, morsure d'animal, coup à la tête ?",
        "Ezali mpota ya lolenge nini : mpota to kokatana, kozika, kokweya to kobukana, kolia ya nyoka, kolia ya nyama, kobeta na motó ?",
        "Yo kele mputa ya mutindu nki : mputa to kuzenga, kuyoka tiya, kubwa to kubukana, kutatika ya nioka, kutatika ya bulu, kubula na ntu ?",
        "Ni jeraha la aina gani: jeraha au mkato, kuungua, kuanguka au mvunjiko, kuumwa na nyoka, kuumwa na mnyama, pigo la kichwani ?",
        "Mputa udi wa mushindu kayi: mputa anyi dikosa, kuosha, kupona anyi kutshibuka, kusuma kua nyoka, kusuma kua nyama, dikuma dia ku mutu ?",
      ),
      type: "choice",
      options: [
        option("cut_wound", t("Plaie ou coupure", "Mpota to kokatana", "Mputa to kuzenga", "Jeraha au mkato", "Mputa anyi dikosa")),
        option("burn", t("Brûlure", "Kozika", "Kuyoka tiya", "Kuungua", "Kuosha")),
        option("fracture_fall", t("Chute ou fracture", "Kokweya to kobukana", "Kubwa to kubukana", "Kuanguka au mvunjiko", "Kupona anyi kutshibuka")),
        option("snakebite", t("Morsure de serpent", "Kolia ya nyoka", "Kutatika ya nioka", "Kuumwa na nyoka", "Kusuma kua nyoka")),
        option("animal_bite", t("Morsure d'animal ou de chien", "Kolia ya nyama to mbwa", "Kutatika ya bulu to mbwa", "Kuumwa na mnyama au mbwa", "Kusuma kua nyama anyi mbua")),
        option("head_injury", t("Coup à la tête", "Kobeta na motó", "Kubula na ntu", "Pigo la kichwani", "Dikuma dia ku mutu")),
      ],
      branches: [
        { when: { q: "injury_type", op: "eq", value: "snakebite" }, next: "snakebite_signs" },
        { when: { q: "injury_type", op: "eq", value: "burn" }, next: "burn_extent" },
        { when: { q: "injury_type", op: "eq", value: "head_injury" }, next: "head_injury_signs" },
      ],
      next: "wound_dirty",
    },
    snakebite_signs: {
      id: "snakebite_signs",
      ask: t(
        "Y a-t-il : gonflement qui monte le long du membre, saignement des gencives, difficulté à respirer, somnolence ou paupières lourdes ?",
        "Ezali na : kovimba oyo ezali komata na loboko to lokolo, makila na minu, kopema mpasi, mpongi to miso ya kilo ?",
        "Kele na : kuvimba yina ke tombuka na diboko to dikulu, menga na meno, kupema mpasi, mpongi to meso ya zitu ?",
        "Kuna: uvimbe unaopanda mkononi au mguuni, damu kwenye ufizi, kupumua kwa shida, usingizi au kope nzito ?",
        "Kudiku: divudi didi dibanda ku tshianza anyi ku dikasa, mashi ku mino, kupetesha lupepele bikole, tulu anyi mêsu makole ?",
      ),
      type: "multi_yes_no",
      options: [
        option("swelling_spreading", t("Gonflement qui monte", "Kovimba ezali komata", "Kuvimba ke tombuka", "Uvimbe unaopanda", "Divudi didi dibanda")),
        option("bleeding_gums", t("Saignement des gencives", "Makila na minu", "Menga na meno", "Damu kwenye ufizi", "Mashi ku mino")),
        option("breathing_difficulty", t("Difficulté à respirer", "Kopema mpasi", "Kupema mpasi", "Kupumua kwa shida", "Kupetesha lupepele bikole")),
        option("drowsy", t("Somnolence, paupières lourdes", "Mpongi, miso ya kilo", "Mpongi, meso ya zitu", "Usingizi, kope nzito", "Tulu, mêsu makole")),
        option("none", t("Aucun de ces signes", "Elembo moko te", "Ata kidimbu mosi ve", "Hakuna dalili yoyote", "Katshina tshimanyinu")),
      ],
      redFlags: [
        { id: "RF-INJ-SNAKE-SWELLING", when: { q: "snakebite_signs", op: "includes", value: "swelling_spreading" }, label: "Œdème progressif après morsure de serpent" },
        { id: "RF-INJ-SNAKE-BLEEDING", when: { q: "snakebite_signs", op: "includes", value: "bleeding_gums" }, label: "Trouble de la coagulation après morsure" },
        { id: "RF-INJ-SNAKE-BREATHING", when: { q: "snakebite_signs", op: "includes", value: "breathing_difficulty" }, label: "Détresse respiratoire après morsure" },
        { id: "RF-INJ-SNAKE-DROWSY", when: { q: "snakebite_signs", op: "includes", value: "drowsy" }, label: "Signes neurologiques après morsure" },
      ],
      onRedFlag: ON_RED_FLAG,
      next: null,
    },
    burn_extent: {
      id: "burn_extent",
      ask: t(
        "La brûlure est-elle : plus petite que la paume de la main, plus grande, sur le visage, les mains ou les parties génitales, ou due à un produit chimique ou à l'électricité ?",
        "Kozika ezali : moke koleka lobɔkɔ, monene koleka, na elongi, maboko to esika ya kobota, to na produit chimique to courant ?",
        "Kuyoka kele : fioti kuluta diboko, nene kuluta, na luse, maboko to kisika ya kubuta, to na kima ya chimique to kura ?",
        "Kuungua ni: ndogo kuliko kiganja, kubwa zaidi, usoni, mikononi au sehemu za siri, au kutokana na kemikali au umeme ?",
        "Kuosha kudi: kukese kupita tshianza, kunene kupita, ku mpala, ku bianza anyi ku bilela, anyi kua tshintu tshia chimique anyi kua kuleji ?",
      ),
      type: "choice",
      options: [
        option("small_palm", t("Plus petite que la paume", "Moke koleka lobɔkɔ", "Fioti kuluta diboko", "Ndogo kuliko kiganja", "Kukese kupita tshianza")),
        option("large", t("Plus grande que la paume", "Monene koleka lobɔkɔ", "Nene kuluta diboko", "Kubwa kuliko kiganja", "Kunene kupita tshianza")),
        option("face_hands_genitals", t("Visage, mains ou parties génitales", "Elongi, maboko to esika ya kobota", "Luse, maboko to kisika ya kubuta", "Uso, mikono au sehemu za siri", "Mpala, bianza anyi bilela")),
        option("chemical_electrical", t("Produit chimique ou électricité", "Produit chimique to courant", "Kima ya chimique to kura", "Kemikali au umeme", "Tshintu tshia chimique anyi kuleji")),
      ],
      redFlags: [
        { id: "RF-INJ-BURN-CHEMICAL", when: { q: "burn_extent", op: "eq", value: "chemical_electrical" }, label: "Brûlure chimique ou électrique" },
      ],
      onRedFlag: ON_RED_FLAG,
      next: "wound_dirty",
    },
    head_injury_signs: {
      id: "head_injury_signs",
      ask: t(
        "Après le coup à la tête, y a-t-il eu : perte de connaissance, vomissements répétés, confusion, liquide clair par le nez ou l'oreille, convulsions ?",
        "Sima ya kobeta na motó, ezalaki na : kokufa mayele, kosanza mbala mingi, kobunga makanisi, mai ya polele na zolo to na litoyi, kobeta nzoto ?",
        "Na nima ya kubula na ntu, kuvandaka na : kufwa mayele, kuluka mbala mingi, kuvila mabanza, masa ya bunkete na mbombo to na kutu, kunikana ?",
        "Baada ya pigo la kichwani, kulikuwa na: kupoteza fahamu, kutapika mara kwa mara, kuchanganyikiwa, maji safi kutoka puani au sikioni, degedege ?",
        "Kunyima kua dikuma dia ku mutu, kuvua ne: kujimija meji, kulua misangu ya bungi, kuvulakana, mâyi mimpe ku diulu anyi ku ditshi, kutshinguluka ?",
      ),
      type: "multi_yes_no",
      options: [
        option("loss_of_consciousness", t("Perte de connaissance", "Kokufa mayele", "Kufwa mayele", "Kupoteza fahamu", "Kujimija meji")),
        option("repeated_vomiting", t("Vomissements répétés", "Kosanza mbala mingi", "Kuluka mbala mingi", "Kutapika mara kwa mara", "Kulua misangu ya bungi")),
        option("confusion", t("Confusion", "Kobunga makanisi", "Kuvila mabanza", "Kuchanganyikiwa", "Kuvulakana")),
        option("clear_fluid", t("Liquide clair par le nez ou l'oreille", "Mai ya polele na zolo to litoyi", "Masa ya bunkete na mbombo to kutu", "Maji safi puani au sikioni", "Mâyi mimpe ku diulu anyi ku ditshi")),
        option("seizure", t("Convulsions", "Kobeta nzoto", "Kunikana", "Degedege", "Kutshinguluka")),
        option("none", t("Aucun de ces signes", "Elembo moko te", "Ata kidimbu mosi ve", "Hakuna dalili yoyote", "Katshina tshimanyinu")),
      ],
      redFlags: [
        { id: "RF-INJ-HEAD-LOC", when: { q: "head_injury_signs", op: "includes", value: "loss_of_consciousness" }, label: "Perte de connaissance après traumatisme crânien" },
        { id: "RF-INJ-HEAD-VOMITING", when: { q: "head_injury_signs", op: "includes", value: "repeated_vomiting" }, label: "Vomissements répétés après traumatisme crânien" },
        { id: "RF-INJ-HEAD-CONFUSION", when: { q: "head_injury_signs", op: "includes", value: "confusion" }, label: "Confusion après traumatisme crânien" },
        { id: "RF-INJ-HEAD-CSF", when: { q: "head_injury_signs", op: "includes", value: "clear_fluid" }, label: "Écoulement clair par le nez ou l'oreille" },
        { id: "RF-INJ-HEAD-SEIZURE", when: { q: "head_injury_signs", op: "includes", value: "seizure" }, label: "Convulsions après traumatisme crânien" },
      ],
      onRedFlag: ON_RED_FLAG,
      next: "wound_dirty",
    },
    wound_dirty: {
      id: "wound_dirty",
      ask: t(
        "La plaie est-elle profonde, sale, ou faite par un objet rouillé ?",
        "Mpota ezali mozindo, ya bosoto, to esalemi na eloko ya rouille ?",
        "Mputa kele ya nda, ya mvindu, to yo salamaka na kima ya rouille ?",
        "Jeraha ni la kina, chafu, au limesababishwa na kitu chenye kutu ?",
        "Mputa udi wa munda, wa mafuta mabi, anyi muenzeka kua tshintu tshia rouille ?",
      ),
      type: "yes_no",
      optional: true,
      next: "tetanus_vaccine",
    },
    tetanus_vaccine: {
      id: "tetanus_vaccine",
      ask: t(
        "La personne est-elle vaccinée contre le tétanos depuis moins de cinq ans ?",
        "Moto azwaki vaccin ya tétanos na mibu mitano oyo eleki ?",
        "Muntu bakaka vaksa ya tetanos na bamvula tanu me luta ?",
        "Je mtu amechanjwa dhidi ya pepopunda ndani ya miaka mitano ?",
        "Muntu wakadi mupete vaksa wa tetanos munda mua bidimu bitanu ?",
      ),
      type: "yes_no",
      optional: true,
      next: null,
    },
  },
  rules: [
    { id: "R-INJ-SNAKEBITE-ANY", when: { q: "injury_type", op: "eq", value: "snakebite" }, severity: 4 },
    { id: "R-INJ-ANIMAL-BITE", when: { q: "injury_type", op: "eq", value: "animal_bite" }, severity: 3 },
    { id: "R-INJ-FRACTURE", when: { q: "injury_type", op: "eq", value: "fracture_fall" }, severity: 3 },
    { id: "R-INJ-HEAD-INJURY", when: { q: "injury_type", op: "eq", value: "head_injury" }, severity: 2 },
    { id: "R-INJ-BURN-LARGE", when: { q: "burn_extent", op: "eq", value: "large" }, severity: 3 },
    { id: "R-INJ-BURN-CRITICAL-AREA", when: { q: "burn_extent", op: "eq", value: "face_hands_genitals" }, severity: 3 },
    { id: "R-INJ-BURN-SMALL", when: { q: "burn_extent", op: "eq", value: "small_palm" }, severity: 1 },
    { id: "R-INJ-DIRTY-WOUND", when: { q: "wound_dirty", op: "eq", value: true }, severity: 2 },
    { id: "R-INJ-TETANUS-NOT-UP-TO-DATE", when: { all: [{ q: "wound_dirty", op: "eq", value: true }, { q: "tetanus_vaccine", op: "eq", value: false }] }, severity: 3 },
  ],
  outcomes: outcomes({
    severity_4: {
      action: "FIRST_AID_THEN_EMERGENCY",
      text: t(
        "Appuyez fort sur la plaie avec un linge propre sans jamais l'enlever, allongez la personne, gardez le membre mordu immobile et plus bas que le cœur, et partez immédiatement au centre de santé ou à l'hôpital le plus proche. Ne posez pas de garrot, ne coupez pas, n'aspirez pas le venin.",
        "Fina makasi na mpota na elamba ya peto mpe kolongola yango te, lalisa moto, tika loboko to lokolo oyo nyoka aswi eningana te mpe na nse ya motema, mpe kende mbala moko na centre de santé to lopitalo. Kokanga na singa te, kokata te, kobenda ngenge te.",
        "Fina ngolo na mputa ti dilele ya bunkete kukatula yo ve, lalisa muntu, bika diboko to dikulu ya nioka tatikaka kunikana ve mpi na nsi ya ntima, mpi kwenda ntangu yayi na centre de santé to lupitalu. Kukanga ti nsinga ve, kuzenga ve, kubenda mibi ve.",
        "Bonyeza kwa nguvu jeraha kwa kitambaa safi bila kukiondoa, mlaze mtu chini, weka kiungo kilichoumwa kikiwa tulivu na chini ya kiwango cha moyo, kisha nenda mara moja kituo cha afya au hospitali. Usifunge kwa kamba, usikate, usinyonye sumu.",
        "Kuata mputa ne bukole ne tshilamba tshimpe kabiyi kutshiumbula, lalika muntu, shiya tshianza anyi dikasa didi disuma kadinyunguluki ne panshi pa mutshima, ne ndaku mpindieu ku tshibambalu tshia bukolame anyi ku lupitadi. Kukanga ne mukaba to, kukosa to, kukupa mulaba to.",
      ),
    },
    severity_1: {
      action: "WOUND_CARE_AT_HOME",
      text: t(
        "Lavez la plaie à l'eau propre et au savon, couvrez-la avec un linge propre et changez le pansement chaque jour. Pour une brûlure, refroidissez sous l'eau propre pendant vingt minutes ; ne mettez ni huile, ni dentifrice, ni herbes. Allez au centre de santé si la plaie rougit, gonfle, coule ou si la fièvre apparaît.",
        "Sukola mpota na mai ya peto mpe sabuni, zipa na elamba ya peto mpe bongola pansement mokolo na mokolo. Mpo na kozika, tia na mai ya peto miniti tuku mibale ; tia mafuta te, dentifrice te, matiti te. Kende na centre de santé soki mpota ekomi motane, evimbi, ebimisi mai to soki fièvre ebimi.",
        "Yobisa mputa ti masa ya bunkete ti sabuni, fika ti dilele ya bunkete mpi soba pansema konso kilumbu. Sambu na kuyoka, tula na masa ya bunkete miniti makumole ; tula mafuta ve, dentifrice ve, matiti ve. Kwenda na centre de santé kana mputa me kuma mbwaki, me vimba, ke basisa masa to kana mwini me basika.",
        "Osha jeraha kwa maji safi na sabuni, funika kwa kitambaa safi na badilisha bandeji kila siku. Kwa kuungua, poza kwa maji safi kwa dakika ishirini; usiweke mafuta, dawa ya meno wala majani. Nenda kituo cha afya jeraha likiwa jekundu, likivimba, likitoa usaha au homa ikitokea.",
        "Owa mputa ne mâyi mimpe ne sabuni, mubuikile ne tshilamba tshimpe ne shintulula tshilamba dituku dionso. Bua kuosha, tekesha ne mâyi mimpe minite makumi abidi; kutedi manyi, dentifrice anyi biyi to. Ndaku ku tshibambalu bikala mputa mukunze, muvule, upatula mafi anyi luya lumueneke.",
      ),
    },
  }),
};
