import { chromium } from "playwright-core";
const [,, url, out, width = "1536", height = "1024", cookie] = process.argv;
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox"] });
const ctx = await browser.newContext({ viewport: { width: Number(width), height: Number(height) }, deviceScaleFactor: 1 });
if (cookie) await ctx.addCookies([{ name: "cvai_session", value: cookie, domain: "localhost", path: "/" }]);
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto(url, { waitUntil: "networkidle", timeout: 120000 });
await page.waitForTimeout(800);
await page.screenshot({ path: out, fullPage: process.env.FULL === "1" });
console.log("saved", out, errors.length ? "errors: " + errors.slice(0, 5).join(" | ") : "no console errors");
await browser.close();
